.storybook/main.ts, stories/Button.stories.ts, stories/Header.stories.ts, stories/Page.stories.ts, stories/Page.tsx, stories/button.css
- use typescript in stories instead
- add ts config in main.ts of storybook
- clean up comments and style
=> chore: rewrite stories with typescript

.gitignore, package-lock.json, package.json, src/components/button/Button.stories.ts, src/components/header/Header.stories.ts, tsconfig.base.json, tsconfig.cjs.json, tsconfig.esm.json
- re-add module configs
- adjust module config base, csj and esm
- test if module config will be bundled in the folder lib
- clean up
=> chore: re-add module and config it properly

package.json
- add override part with specific version of ts for react scripts
=> fix: add override in package.json with ts for react scripts

package.json
- add script for build tailwind css in esm and cjs module
=> chore: add tailwind css to module

README.md, package.json
- add authors and license to package
- add commands to readme
=> docs: update readme, add authors and license to package

package.json
- add organization
- set to public
=> chore: package release readiness

.github/workflows/release.yaml
- semantic npm package release with github workflows
=> chore: setup semantic release

.github/workflows/release.yaml, package-lock.json, package.json
- add semantic release package
- set main as default branch in package
=> fix: extend semantic release and package config

package-lock.json, package.json, src/components/button/index.ts, src/components/header/index.ts, src/components/index.ts, src/components/page/index.ts, src/index.tsx
- use barrel solution for the import component in web app
=> chore: use barrel solution for import component properly in webapp

src/components/button/Button.tsx, src/components/header/Header.tsx, src/components/page/Page.tsx, src/index.tsx
- change components signature to client
=> fix: make client components

package.json
- set package version to 0.1.0 so it updates automatically
=> fix: npm package version

src/components/index.ts
- because there is an export issue we use the single component for now
=> fix: fix the export rule because of single comp

src/components/button/index.ts, src/components/index.ts, src/index.tsx
- add use client in right file
- check if that works with the binding button in web app
=> fix: clean up and set use client in right place

LICENCE, package.json
- add licence
- rename licence in the package.json to MIT
=> chore: add licence

README.md
- add some project shield for getting deploy info from github
=> chore: add project shields github

README.md
- fix the path for the shield of sb deploy (github pages)
=> fix: fix the path shield for sb deploy

src/components/index.ts, src/components/link-button/LinkButton.stories.ts, src/components/link-button/LinkButton.tsx, src/components/link-button/index.ts, src/index.ts, src/index.tsx
- add second component: linkbutton
=> feat: add linkbutton

src/components/link-button/index.ts
- correct the index for the link button
=> fix: correct the index for link button

package.json
- add the missed tailwind export module config
=> feat: add tailwind export config

package.json
- remove no needed tailwind in the file scope of package config
=> fix: remove tailwind from file in package config

.github/workflows/deploy-storybook.yaml
- rename build storybook reference in workflow for pages deployment
=> fix(deploy-storybook): rename storybook reference

.gitignore, package-lock.json, package.json
- update npm package
- fix linting
- cleanup
=> chore: update npm package

.husky/commit-msg, LICENCE, README.md, commitlint.config.js, package.json
- fix url in README.md (TS)
- correct the text in licence
- add keywords in package
- update roadmap
- add commit lint message quality
=> chore: clean up readme

README.md
- adjust new path yaml file name for shields badge info in the readme
=> chore(adjust-path-badge-info): adjust path workflow

.github/workflows/3-deploy-storybook.yaml, .github/workflows/4-release.yaml, README.md
- set node version to 18 on workflows
=> fix: set node version to 18

.storybook/pixelPioneersTheme.ts
- adjust colors which suits to the mumble project
=> docs(storybook-theme): adjust colors

.storybook/main.ts, .storybook/preview.ts, .storybook/storybook.css, src/docs/colors.mdx
=> docs(colors): add colors doc style

docs/STYLING.md, src/docs/spacing.mdx
=> docs(spacing): add spacing style doc

docs/intro.md, src/docs/borders.mdx
=> docs(borders): add border doc

src/components/typography/index.ts, src/components/typography/placeholder/index.ts, src/components/typography/placeholder/placeholder.stories.ts, src/components/typography/placeholder/placeholder.tsx, src/components/typography/placeholder/types.ts
- add placeholder a new typographie
=> feat(typographie-placeholder): add placeholder

.storybook/main.ts, package-lock.json, package.json, src/components/avatar/avatar.stories.ts, src/components/button/button.stories.ts, src/components/form/file-upload/file-upload.stories.ts, src/components/form/input/input.stories.ts, src/components/form/textarea/textarea.stories.ts, src/components/icon-button/icon-button.stories.ts, src/components/icon-link/icon-link.stories.ts, src/components/interactive-button/comment-button.stories.ts, src/components/interactive-button/interactive-button.stories.ts, src/components/interactive-button/like-button.stories.ts, src/components/interactive-button/share-button.stories.ts, src/components/navi-button/navi-button.stories.ts, src/components/tabs/tabs.stories.ts, src/components/text-link/text-link.stories.ts, src/components/typography/heading/heading.stories.ts, src/components/typography/label/label.stories.ts, src/components/typography/paragraph/paragraph.stories.ts, src/components/typography/placeholder/placeholder.stories.ts, src/docs/borders.mdx, src/docs/colors.mdx, src/docs/spacing.mdx, src/elements/branding/branding.stories.tsx, src/elements/icons/icons.stories.tsx
- add addon-design and link with figma in all stories
- storybook: design integration
=> docs(cleanup-stories): add addon-design and link

README.md
- remove roadmap chapter from table content
=> feat(clean-up-table-content): remove chapter

.eslintrc.json, .gitignore, README.md, package.json, src/components/avatar/avatar.tsx, src/components/avatar/edit-avatar.tsx, src/components/avatar/types.ts, src/components/form/file-upload/file-upload.tsx, src/components/form/file-upload/types.ts, src/components/interactive-button/like-button.tsx, src/components/interactive-button/types.ts, src/components/modal/modal.stories.tsx, src/components/modal/modal.tsx, src/components/modal/types.ts, src/components/typography/heading/heading.stories.ts, src/components/typography/heading/heading.tsx, src/components/typography/heading/types.ts, src/elements/branding/branding.stories.tsx, src/utlis/helpers.ts
- improve gitignore extension
- correct modal with naming
- correct readme
- remove private in package.json (private - false is per default)
- remove unused access modifier export in types.ts file
- improve typescript operator for onClick
- improve heading code
- add console logs check in eslint
- improve upload form code
- improve util file code
- remove unused className in Avatar / Edit Avatar
=> feat(feedback-improvements): improve code review feedbacks

src/components/avatar/edit-avatar.stories.ts, src/components/avatar/edit-avatar.tsx, src/components/avatar/types.ts, src/components/form/file-upload/file-upload.tsx, src/components/modal/modal.stories.tsx
- add preview placeholder for the upload image component
- add small avatar edit size for mobile view
- extend sample of avatar edit size in storybook
- increase file size example in storybook - upload modal
=> feat(add-image-preview): add upload preview placeholder and add avatar edit for mobile
